name: Maybe-fail

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        return-code:
          - 0
          - 1
        continue-on-failure:
          - true
          - false
      fail-fast: false
    name: Maybe fail
    steps:
      - uses: actions/checkout@v4
      - name: Use maybe-fail action
        id: maybe-fail
        uses: ./maybe-fail
        with:
          return-code: ${{ matrix.return-code }}
          continue-on-failure: ${{ matrix.continue-on-failure }}
      - name: After Action
        if: success() || failure()
        env:
          conclusion: ${{ steps.maybe-fail.conclusion }}
          outcome: ${{ steps.maybe-fail.outcome}}
          result: ${{ steps.maybe-fail.outputs.result }}
        run: |
          (
            echo "outcome: $outcome"
            echo "conclusion: $conclusion"
            echo "result: $result"
            echo
          ) | tee -a "$GITHUB_STEP_SUMMARY"
      - name: Next Step
        run:
          echo Next step | tee -a "$GITHUB_STEP_SUMMARY"
