name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Debug action
        run: grep -n . ./action.yml

      - name: Run action
        uses: ./
      - name: Run action
        uses: ./
      - name: Run action
        uses: ./
      - name: Run action
        uses: ./
      - name: Run action
        uses: ./
      - name: Run action
        uses: ./
