name: 'Maybe fail'
description: 'Conditionally fail based on inputs'
inputs:
  return-code:
    description: 'Value to use as exit code for main step'
    required: false
    default: '0'
  continue-on-error:
    description: 'Whether to run the main step with `continue-on-error`'
    required: false
    default: 'false'
outputs:
  result:
    description: "Result for posterity"
    value: ${{ steps.report-outcome.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Run step if continue-on-error = false
      id: continue-on-error-false
      if: ${{ inputs.continue-on-error == 'false' }}
      continue-on-error: false
      run: exit ${{ inputs.return-code }}
      shell: bash
    - name: Run step if continue-on-error != false
      id: continue-on-error-true
      if: ${{ inputs.continue-on-error != 'false' }}
      continue-on-error: true
      run: exit ${{ inputs.return-code }}
      shell: bash
    - id: report-outcome
      if: success() || failure()
      run: echo "result=$outcome" | tee -a "$GITHUB_OUTPUT"
      env:
        outcome: ${{ steps.continue-on-error-false.outcome != 'skipped' && steps.continue-on-error-false.outcome || steps.continue-on-error-true.outcome }}
      shell: bash
